# -*- coding: utf-8 -*-
"""streamlit_web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IWLnInfrZ0yyfYBZnEGw9wna2YL435f3
"""

!pip install streamlit shapely folium quackosm pyngrok folium

import streamlit as st
import streamlit.components.v1 as components
from shapely.geometry import box
import quackosm as qosm
import tempfile
import os
import folium
import shapely
from pyngrok import ngrok
import geopandas as gpd
ngrok.set_auth_token("3ExFKo1Ai0PgC41H375owXyvtDW_6sEMWGRkFnHJ58xEbgfqu")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import streamlit.components.v1 as components
# from shapely.geometry import box
# from shapely.geometry.polygon import orient
# import quackosm as qosm
# import tempfile
# import os
# import numpy as np
# import pandas as pd
# import geopandas as gpd
# import folium
# import shapely
# import torch
# from torch import nn
# from sklearn.preprocessing import LabelEncoder, StandardScaler
# from sklearn.impute import SimpleImputer
# 
# CLASS_NAMES = {
#     0: 'allotment_house', 1: 'apartments', 2: 'barn', 3: 'bungalow', 4: 'bunker',
#     5: 'carport', 6: 'chapel', 7: 'church', 8: 'civic', 9: 'college',
#     10: 'commercial', 11: 'construction', 12: 'cowshed', 13: 'detached', 14: 'dormitory',
#     15: 'farm', 16: 'farm_auxiliary', 17: 'garage', 18: 'garages', 19: 'gatehouse',
#     20: 'government', 21: 'greenhouse', 22: 'guardhouse', 23: 'hangar', 24: 'hospital',
#     25: 'hotel', 26: 'house', 27: 'hut', 28: 'industrial', 29: 'kindergarten',
#     30: 'kiosk', 31: 'military', 32: 'mosque', 33: 'office', 34: 'parking',
#     35: 'pavilion', 36: 'public', 37: 'residential', 38: 'retail', 39: 'roof',
#     40: 'ruins', 41: 'school', 42: 'semidetached_house', 43: 'service', 44: 'shed',
#     45: 'storage_tank', 46: 'terrace', 47: 'train_station', 48: 'transportation',
#     49: 'university', 50: 'warehouse'
# }
# 
# device = "cuda" if torch.cuda.is_available() else "cpu"
# 
# class ClassificNet(nn.Module):
#     def __init__(self, in_features, hidden_features, num_classes):
#         super().__init__()
#         self.model = nn.Sequential(
#             nn.Linear(in_features, hidden_features),
#             nn.GELU(),
#             nn.Linear(hidden_features, hidden_features * 4),
#             nn.GELU(),
#             nn.Linear(hidden_features * 4, hidden_features),
#             nn.GELU(),
#             nn.Linear(hidden_features, num_classes)
#         )
#     def forward(self, x):
#         return self.model(x)
# 
# class FeatureTokenizer(nn.Module):
#     def __init__(self, n_features, d_token):
#         super().__init__()
#         self.weight = nn.Parameter(torch.Tensor(n_features, d_token))
#         self.bias = nn.Parameter(torch.Tensor(n_features, d_token))
#         nn.init.xavier_uniform_(self.weight)
#         nn.init.zeros_(self.bias)
#     def forward(self, x):
#         return x.unsqueeze(-1) * self.weight.unsqueeze(0) + self.bias.unsqueeze(0)
# 
# class TransformerBlock(nn.Module):
#     def __init__(self, d_model, n_heads, dropout, mlp_mult=4.0):
#         super().__init__()
#         self.norm1 = nn.LayerNorm(d_model)
#         self.attn = nn.MultiheadAttention(d_model, n_heads, dropout=dropout, batch_first=True)
#         self.norm2 = nn.LayerNorm(d_model)
#         self.mlp = nn.Sequential(
#             nn.Linear(d_model, int(d_model * mlp_mult)),
#             nn.GELU(),
#             nn.Linear(int(d_model * mlp_mult), d_model),
#         )
#     def forward(self, x):
#         residual = x
#         x = self.norm1(x)
#         x = self.attn(x, x, x, need_weights=False)[0]
#         x = residual + x
#         residual = x
#         x = self.norm2(x)
#         x = self.mlp(x)
#         return residual + x
# 
# class Transformer(nn.Module):
#     def __init__(self, d_model, n_heads, depth, dropout, mlp_mult=4.0):
#         super().__init__()
#         self.blocks = nn.ModuleList([TransformerBlock(d_model, n_heads, dropout, mlp_mult) for _ in range(depth)])
#         self.norm = nn.LayerNorm(d_model)
#     def forward(self, x):
#         for block in self.blocks:
#             x = block(x)
#         return self.norm(x)
# 
# class FTTransformer(nn.Module):
#     def __init__(self, n_features, num_classes, d_token=96, depth=6, n_heads=4, dropout=0.0, mlp_mult=4.0):
#         super().__init__()
#         self.tokenizer = FeatureTokenizer(n_features, d_token)
#         self.cls_token = nn.Parameter(torch.randn(1, 1, d_token) * 0.02)
#         self.transformer = Transformer(d_token, n_heads, depth, dropout, mlp_mult)
#         self.head = nn.Linear(d_token, num_classes)
#         nn.init.zeros_(self.head.weight)
#         nn.init.zeros_(self.head.bias)
#     def forward(self, x):
#         tokens = torch.cat([self.cls_token.expand(x.shape[0], -1, -1), self.tokenizer(x)], dim=1)
#         return self.head(self.transformer(tokens)[:, 0, :])
# 
# st.title("OSM Buildings Tagger")
# 
# _, col, _ = st.columns(3)
# with col:
#     north_Y = st.text_input("North (широта)", placeholder="например: 58.5", width=200)
# 
# col1, col2 = st.columns(2)
# with col1:
#     west_X = st.text_input("West (долгота)", placeholder="например: 41.5", width=200)
# with col2:
#     east_X = st.text_input("East (долгота)", placeholder="например: 42.0", width=200)
# 
# _, col, _ = st.columns(3)
# with col:
#     south_Y = st.text_input("South (широта)", placeholder="например: 57.5", width=200)
# 
# model_choice = st.selectbox("Модель", ["MLP", "FTTransformer"])
# 
# def compute_features(gdf):
#     buildings = gdf.to_crs(3587)
#     buildings['geometry'] = buildings['geometry'].apply(lambda geom: orient(geom, sign=1.0))
# 
#     buildings['area'] = buildings.geometry.area
#     buildings['perimeter'] = buildings.geometry.length
#     buildings['compactness'] = buildings['perimeter'] / np.sqrt(buildings['area'])
#     buildings['compactness_index'] = (4 * np.pi * buildings['area'] / buildings['perimeter'] ** 2).replace([np.inf, -np.inf], 0).fillna(0)
# 
#     if 'building:levels' in buildings.columns:
#         buildings['level_count'] = pd.to_numeric(buildings['building:levels'], errors='coerce').fillna(1).astype(int)
#     else:
#         buildings['level_count'] = 1
# 
#     mbr_areas, mbr_lengths, mbr_widths = [], [], []
#     for geom in buildings.geometry:
#         mbr = geom.minimum_rotated_rectangle
#         if mbr.geom_type == 'Polygon' and not mbr.is_empty:
#             coords = list(mbr.exterior.coords)
#             a = np.sqrt((coords[0][0]-coords[1][0])**2+(coords[0][1]-coords[1][1])**2)
#             b = np.sqrt((coords[1][0]-coords[2][0])**2+(coords[1][1]-coords[2][1])**2)
#             mbr_areas.append(mbr.area)
#             mbr_lengths.append(max(a,b))
#             mbr_widths.append(min(a,b))
#         else:
#             mbr_areas.append(0)
#             mbr_lengths.append(0)
#             mbr_widths.append(0)
# 
#     buildings['mbr_area'] = mbr_areas
#     buildings['mbr_length'] = mbr_lengths
#     buildings['mbr_width'] = mbr_widths
#     buildings['rectangularity'] = (buildings['area'] / buildings['mbr_area']).replace([np.inf, -np.inf], 0).fillna(0)
#     buildings['elongatedness'] = (buildings['mbr_length'] / buildings['mbr_width']).replace([np.inf, -np.inf], 1).fillna(1)
# 
#     convex = buildings.geometry.convex_hull
#     buildings['convex_hull_area'] = convex.area
#     buildings['convex_hull_perimeter'] = convex.length
#     buildings['convexity'] = (buildings['area'] / buildings['convex_hull_area']).replace([np.inf, -np.inf], 1).fillna(1)
#     buildings['sinuosity'] = (buildings['convex_hull_perimeter'] / buildings['perimeter']).replace([np.inf, -np.inf], 1).fillna(1)
# 
#     buildings['vertex_count'] = buildings.geometry.apply(
#         lambda g: len(g.exterior.coords) if g.geom_type == 'Polygon' else 0
#     )
# 
#     def count_convex_corners(geom):
#         if geom.geom_type != 'Polygon':
#             return 0
#         coords = list(geom.exterior.coords)[:-1]
#         n = len(coords)
#         count = 0
#         for i in range(n):
#             p0 = np.array(coords[i - 1])
#             p1 = np.array(coords[i])
#             p2 = np.array(coords[(i + 1) % n])
#             if np.cross(p0 - p1, p2 - p1) > 0:
#                 count += 1
#         return count
# 
#     buildings['convex_vertex_count'] = buildings.geometry.apply(count_convex_corners)
#     buildings['convex_vertex_ratio'] = (
#         buildings['convex_vertex_count'] / buildings['vertex_count']
#     ).replace([np.inf, -np.inf], 0).fillna(0)
# 
#     buildings['inscribed_radius'] = buildings.geometry.apply(
#         lambda g: shapely.maximum_inscribed_circle(g).length if g.geom_type == 'Polygon' and not g.is_empty else 0.0
#     )
#     buildings['inscribed_area_ratio'] = np.where(
#         buildings['area'] > 0, np.pi * buildings['inscribed_radius'] ** 2 / buildings['area'], 0.0
#     )
# 
#     buildings['enclosed_radius'] = buildings.geometry.apply(
#         lambda g: shapely.minimum_bounding_radius(g) if g.geom_type == 'Polygon' and not g.is_empty else 0.0
#     )
#     buildings['enclosed_area_ratio'] = np.where(
#         buildings['enclosed_radius'] > 0, buildings['area'] / (np.pi * buildings['enclosed_radius'] ** 2), 0.0
#     )
#     buildings['circular_variance'] = np.where(
#         buildings['enclosed_radius'] > 0, buildings['inscribed_radius'] / buildings['enclosed_radius'], 0.0
#     )
# 
#     buildings['floor_area'] = buildings['level_count'] * buildings['area']
#     buildings['height_ratio'] = 2.7 * buildings['level_count'] / buildings['area'] ** 0.5
#     buildings['hole_count'] = buildings.geometry.apply(
#         lambda g: len(list(g.interiors)) if g.geom_type == 'Polygon' else 0
#     )
# 
#     centroid = buildings.geometry.centroid
#     rep_pt = buildings.geometry.representative_point()
#     buildings['normalized_centroid_offset'] = centroid.distance(rep_pt) / np.sqrt(buildings['area'])
# 
#     buildings = buildings.rename(columns={
#         'mbr_area': 'area_MRR',
#         'mbr_length': 'length',
#         'mbr_width': 'width',
#         'convex_area': 'convex_hull_area',
#         'convex_perimeter': 'convex_hull_perimeter',
#     })
#     buildings['floor_area'] = buildings['level_count'] * buildings['area']
#     buildings['height_ratio'] = 2.7 * buildings['level_count'] / buildings['area'] ** 0.5
#     numeric_cols = buildings.select_dtypes(include=[np.number]).columns
#     buildings[numeric_cols] = buildings[numeric_cols].replace([np.inf, -np.inf], np.nan)
#     buildings[numeric_cols] = buildings[numeric_cols].fillna(0)
# 
#     return buildings
# 
# FEATURE_COLS = [
#     'level_count', 'area', 'area_MRR', 'length', 'width', 'perimeter',
#     'compactness', 'compactness_index', 'rectangularity', 'elongatedness',
#     'convex_hull_area', 'convex_hull_perimeter', 'convexity', 'sinuosity',
#     'vertex_count', 'convex_vertex_count', 'convex_vertex_ratio',
#     'inscribed_radius', 'inscribed_area_ratio', 'enclosed_radius',
#     'enclosed_area_ratio', 'circular_variance', 'floor_area', 'height_ratio',
#     'hole_count', 'normalized_centroid_offset'
# ]
# 
# def run_model(gdf, model_type):
#     df = pd.DataFrame(gdf)
# 
#     if 'building' in df.columns:
#         original_classes = df['building'].fillna('unknown').values
#     else:
#         original_classes = ['unknown'] * len(df)
# 
#     X = df[FEATURE_COLS].astype('float64').values
#     X = np.where(np.isinf(X), np.nan, X)
#     imputer = SimpleImputer(strategy='mean')
#     X = imputer.fit_transform(X)
# 
#     if not np.isfinite(X).all():
#         X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)
# 
#     scaler = StandardScaler()
#     X_sc = scaler.fit_transform(X)
# 
#     class GeoDataset(torch.utils.data.Dataset):
#         def __init__(self, x):
#             self.x = x
#         def __len__(self):
#             return len(self.x)
#         def __getitem__(self, idx):
#             return torch.tensor(self.x[idx], dtype=torch.float)
# 
#     loader = torch.utils.data.DataLoader(GeoDataset(X_sc), batch_size=256, shuffle=False)
# 
#     num_classes = 51
#     if model_type == "MLP":
#         model = ClassificNet(len(FEATURE_COLS), 128, num_classes).to(device)
#         model_path = '/content/drive/MyDrive/model_trained.pt'
#     else:
#         model = FTTransformer(n_features=len(FEATURE_COLS), num_classes=num_classes).to(device)
#         model_path = '/content/drive/MyDrive/ftt_model.pt'
# 
#     state_dict = torch.load(model_path, weights_only=True, map_location='cpu')
#     model.load_state_dict(state_dict)
#     model.eval()
# 
#     all_outputs = []
#     with torch.no_grad():
#         for objects in loader:
#             all_outputs.append(model(objects.to(device)).cpu())
#     y_pred_numeric = torch.argmax(torch.cat(all_outputs, dim=0), dim=1).numpy()
#     predicted_names = [CLASS_NAMES.get(i, str(i)) for i in y_pred_numeric]
# 
#     return predicted_names, original_classes
# 
# @st.cache_data(ttl=3600, show_spinner=False)
# def load_process_data(north, south, west, east):
#     bbox = box(float(west), float(south), float(east), float(north))
#     with st.spinner("Загрузка данных из OSM PBF..."):
#         gdf = qosm.convert_pbf_to_geodataframe(
#             "/content/drive/MyDrive/OSM.pbf",
#             tags_filter={"building": True},
#             geometry_filter=bbox,
#             keep_all_tags=True
#         )
#     if len(gdf) == 0:
#         return gdf
#     return compute_features(gdf)
# 
# if st.button("Загрузить и классифицировать", type="primary"):
#     if all([north_Y, south_Y, west_X, east_X]):
#         try:
#             north = float(north_Y)
#             south = float(south_Y)
#             west = float(west_X)
#             east = float(east_X)
# 
#             if north <= south:
#                 st.error("North должно быть больше South")
#             elif east <= west:
#                 st.error("East должно быть больше West")
#             else:
#                 gdf = load_process_data(north, south, west, east)
# 
#                 if len(gdf) == 0:
#                     st.warning("В указанной области не найдено зданий")
#                 else:
#                     st.success(f"Загружено {len(gdf)} зданий")
# 
#                     with st.spinner("Классификация..."):
#                         pred_labels, original_classes = run_model(gdf, model_choice)
#                         gdf['predicted_class'] = pred_labels
#                         gdf['original_class'] = original_classes
# 
#                     all_classes = sorted(gdf['predicted_class'].unique())
#                     palette = [
#                         '#e6194b','#3cb44b','#ffe119','#4363d8','#f58231',
#                         '#911eb4','#42d4f4','#f032e6','#bfef45','#fabed4',
#                         '#469990','#dcbeff','#9a6324','#fffac8','#800000',
#                         '#aaffc3','#808000','#ffd8b1','#000075','#a9a9a9'
#                     ]
#                     color_map = {cls: palette[i % len(palette)] for i, cls in enumerate(all_classes)}
# 
#                     with st.spinner("Построение карты..."):
#                         gdf_wgs84 = gdf.to_crs(4326)
#                         center = [gdf_wgs84.geometry.centroid.y.mean(), gdf_wgs84.geometry.centroid.x.mean()]
#                         m = folium.Map(location=center, zoom_start=15)
# 
#                         for idx, row in gdf_wgs84.iterrows():
#                             color = color_map.get(row['predicted_class'], '#888888')
#                             popup_html = f"""
#                             <div style="min-width:220px;font-family:sans-serif;font-size:13px">
#                                 <b>Оригинальный класс:</b> {row['original_class']}<br>
#                                 <b>Предсказанный класс:</b> {row['predicted_class']}<br>
#                                 <hr style="margin:4px 0">
#                                 <b>Площадь:</b> {row['area']:.1f} м²<br>
#                                 <b>Этажей:</b> {row['level_count']}<br>
#                                 <b>Компактность:</b> {row['compactness_index']:.3f}<br>
#                                 <b>Прямоугольность:</b> {row['rectangularity']:.3f}<br>
#                                 <b>Вытянутость:</b> {row['elongatedness']:.2f}<br>
#                                 <b>Округлость:</b> {row['circular_variance']:.3f}<br>
#                                 <b>Вершин:</b> {row['vertex_count']}<br>
#                                 <b>Дыр:</b> {row['hole_count']}
#                             </div>
#                             """
#                             folium.GeoJson(
#                                 row['geometry'].__geo_interface__,
#                                 style_function=lambda x, c=color: {
#                                     'fillColor': c,
#                                     'color': '#333333',
#                                     'weight': 1,
#                                     'fillOpacity': 0.7
#                                 },
#                                 popup=folium.Popup(popup_html, max_width=300)
#                             ).add_to(m)
# 
#                         legend_html = '<div style="position:fixed;bottom:30px;left:30px;z-index:1000;background:white;padding:10px;border-radius:6px;font-size:12px;font-family:sans-serif;max-height:300px;overflow-y:auto">'
#                         for cls, clr in color_map.items():
#                             legend_html += f'<div><span style="display:inline-block;width:14px;height:14px;background:{clr};margin-right:6px;border-radius:2px"></span>{cls}</div>'
#                         legend_html += '</div>'
#                         m.get_root().html.add_child(folium.Element(legend_html))
# 
#                         with tempfile.NamedTemporaryFile(delete=False, suffix='.html') as tmp:
#                             m.save(tmp.name)
#                             tmp_path = tmp.name
#                         with open(tmp_path, 'r', encoding='utf-8') as f:
#                             components.html(f.read(), height=600, width=1000)
#                         os.unlink(tmp_path)
# 
#                     with st.expander("Распределение предсказанных классов"):
#                         counts = gdf['predicted_class'].value_counts().reset_index()
#                         counts.columns = ['Класс', 'Количество']
#                         st.dataframe(counts)
# 
#         except Exception as e:
#             st.error(f"Ошибка: {str(e)}")
#             st.exception(e)
#     else:
#         st.warning("Заполните все поля с координатами")

ngrok.set_auth_token("3ExFKo1Ai0PgC41H375owXyvtDW_6sEMWGRkFnHJ58xEbgfqu")

ngrok.kill()

public_url = ngrok.connect(8501)
print(public_url)